# Generated by Django 3.2.7 on 2022-11-07 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='講座タイトル')),
                ('detail', models.CharField(max_length=500, verbose_name='講座詳細')),
                ('course_img', models.ImageField(blank=True, max_length=30, null=True, upload_to='', verbose_name='イメージ画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256, verbose_name='メールアドレス')),
                ('user_name', models.CharField(max_length=500, verbose_name='名前')),
                ('inquiry_content', models.CharField(max_length=500, verbose_name='お問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name_plural': 'Inquiry',
            },
        ),
        migrations.CreateModel(
            name='Skillseat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='名前')),
                ('gender', models.CharField(max_length=5, verbose_name='性別')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('user_img', models.ImageField(blank=True, max_length=30, null=True, upload_to='', verbose_name='プロフィール画像')),
                ('user_evaluation', models.FloatField(blank=True, max_length=2, null=True, verbose_name='評価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'Skillseat',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='メッセージ')),
                ('request_completed', models.BooleanField(blank=True, null=True, verbose_name='依頼成立')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('course_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to='skillswap.course', verbose_name='講座ID')),
                ('user_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='送信者ID')),
            ],
            options={
                'verbose_name_plural': 'Request',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_detail', models.CharField(max_length=500, verbose_name='お知らせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_1', models.CharField(max_length=100, verbose_name='ジャンル大')),
                ('genre_2', models.CharField(max_length=100, verbose_name='ジャンル小')),
                ('career', models.CharField(blank=True, max_length=100, null=True, verbose_name='経歴')),
                ('language_detail', models.CharField(blank=True, max_length=500, null=True, verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('course_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to='skillswap.course', verbose_name='講座ID')),
                ('user_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name_plural': 'Favorite',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_num', models.IntegerField(verbose_name='評価')),
                ('evaluation_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='レビュー文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user1_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='user1_eva', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー1ID')),
                ('user2_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='user2_eva', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー2ID')),
            ],
            options={
                'verbose_name_plural': 'Evaluation',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='メッセージ')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='static/files/', verbose_name='ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('request_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to='skillswap.request', verbose_name='依頼ID')),
                ('user_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='送信者ID')),
            ],
            options={
                'verbose_name_plural': 'Chat',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='user1_block', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー1ID')),
                ('user2_id', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='user2_block', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー2ID')),
            ],
            options={
                'verbose_name_plural': 'Block',
            },
        ),
    ]
