# Generated by Django 3.2.7 on 2022-11-07 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillswap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_id',
            field=models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='user_id',
            field=models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='skillseat',
            name='user_id',
            field=models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
    ]
