# Generated by Django 3.2.7 on 2022-11-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap', '0003_alter_language_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillseat',
            name='age',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='生年月日'),
        ),
    ]
