# Generated by Django 3.2.7 on 2022-11-18 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillswap', '0005_skillseat_profile_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillseat',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
    ]
