# Generated by Django 3.2.7 on 2022-11-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap', '0006_auto_20221118_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillseat',
            name='age',
        ),
    ]
