# Generated by Django 3.2.7 on 2022-11-29 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillswap', '0007_remove_skillseat_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='receiver_id',
            field=models.ForeignKey(default=2, max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_id', to='accounts.customuser', verbose_name='ユーザー受信者ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー送信者ID'),
        ),
    ]
