# Generated by Django 3.2.7 on 2023-01-17 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillswap', '0009_friends_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='replied',
            field=models.BooleanField(blank=True, null=True, verbose_name='返信の有無'),
        ),
        migrations.AddField(
            model_name='news',
            name='reply_all',
            field=models.BooleanField(blank=True, null=True, verbose_name='全員へ返信'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user_id',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
    ]
