# Generated by Django 3.2.7 on 2023-01-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap', '0010_auto_20230117_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='review_completed',
            field=models.BooleanField(blank=True, null=True, verbose_name='レビュー完了'),
        ),
    ]
