# Generated by Django 3.2.7 on 2023-02-03 04:57

from django.db import migrations, models
import skillswap.models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap', '0011_friends_review_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.CharField(max_length=500, validators=[skillswap.models.validate_bad_word], verbose_name='講座詳細'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, validators=[skillswap.models.validate_bad_word], verbose_name='講座タイトル'),
        ),
    ]
