# Generated by Django 3.2.7 on 2023-02-07 00:48

from django.db import migrations, models
import skillswap.models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswap', '0012_auto_20230203_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=500, validators=[skillswap.models.validate_bad_word], verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='evaluation_text',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[skillswap.models.validate_bad_word], verbose_name='レビュー文'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_content',
            field=models.CharField(max_length=500, validators=[skillswap.models.validate_bad_word], verbose_name='お問い合わせ内容'),
        ),
        migrations.AlterField(
            model_name='language',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[skillswap.models.validate_bad_word], verbose_name='経歴'),
        ),
        migrations.AlterField(
            model_name='language',
            name='genre_1',
            field=models.CharField(max_length=100, validators=[skillswap.models.validate_bad_word], verbose_name='ジャンル大'),
        ),
        migrations.AlterField(
            model_name='language',
            name='genre_2',
            field=models.CharField(max_length=100, validators=[skillswap.models.validate_bad_word], verbose_name='ジャンル小'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_detail',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[skillswap.models.validate_bad_word], verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='description',
            field=models.TextField(validators=[skillswap.models.validate_bad_word]),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_detail',
            field=models.CharField(max_length=500, validators=[skillswap.models.validate_bad_word], verbose_name='お知らせ内容'),
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.CharField(max_length=500, validators=[skillswap.models.validate_bad_word], verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='skillseat',
            name='profile_text',
            field=models.CharField(default='よろしくお願いします', max_length=10000, validators=[skillswap.models.validate_bad_word], verbose_name='プロフィール文章'),
        ),
        migrations.AlterField(
            model_name='skillseat',
            name='user_name',
            field=models.CharField(max_length=30, validators=[skillswap.models.validate_bad_word], verbose_name='名前'),
        ),
    ]
